### ISSUE TITLE
FPGA controls system's API

### ISSUE THREAD

**Issue by astralien3000** [Sokario/Silver#1]
Let's organize the API as in this [document](https://github.com/astralien3000/robot-control-tuto/tree/master/2wheel). Here is my first proposition : 
```c
////////////////////////////////
// Layer 0
u16 motor_left;
u16 motor_right;

u32 encoder_left;
u32 encoder_right;

////////////////////////////////
// Layer 1
u32 motc_left;
u32 motc_right;

//// Configuration
u32 motc_*_p;
u32 motc_*_i;
u32 motc_*_d;

////////////////////////////////
// Layer 2
u32 diff_dangle;
u32 diff_speed;

u32 odo_angle;
u32 odo_distance;

//// Config ? TODO

////////////////////////////////
// Layer 3
u32 angle;
u32 speed;

//// Configuration
u32 *_p;
u32 *_i;
u32 *_d;

////////////////////////////////
// Layer 4
u32 speed_x;
u32 speed_y;

u32 x;
u32 y;

//// Config ? TODO
```

What do you think of this ?
Would you rather use upper case ? Other names/types ?

**Comment by Sokario** [comment]
Its what I thinking about the API but I can't tell if it will be exactly this one. Indeed I don't understand why you use unsigned integer while you can have negative value.
So at this point I create the motor driver and I choose to encode input data on 32 signed bits (This is the encode format of input in logic but it would be signed int in the "os" point of view).
Its the same about encoder driver, I choose output data to be encode on 32 signed bits.

So the layer 0 is more like that for the moment:
////////////////////////////////
// Layer 0
s32 motor_left;
s32 motor_right;

s32 encoder_left;
s32 encoder_right;

**Comment by astralien3000** [comment]
Ah ! Yes, I did a mistake. Almost every `u**` should be replaced by a `s**` in my proposition.
Ok for Layer 0.
Encoders are better signed to avoid underflows when counters are near 0.
Motors are of course signed, and 32 bits makes the control supposed to be more precise. Maybe 32 bits is even "too much", but it can't be bad.

**Comment by Sokario** [comment]
the 32 bits are because of the register size of the axis lite structure but indeed it's too much.
On the other hand, we don't have to use the full variable length. If it's possible I may be concatenate the too motor's command in single variable but it not my purpose for the moment.
